#include "Main.h"


void showSubtitle(const char* text)
{
    UILOG::_UILOG_SET_CACHED_OBJECTIVE(MISC::VAR_STRING(10, "LITERAL_STRING", text));
    UILOG::_UILOG_PRINT_CACHED_OBJECTIVE();
    UILOG::_UILOG_CLEAR_CACHED_OBJECTIVE();
}